data:extend({
  {
    type = "int-setting",
    name = "beltometer-default-window-size",
    setting_type = "runtime-global",
    default_value = 60,
    minimum_value = 1,
    maximum_value = 6000,
    order = "a",
  },
  {
    type = "string-setting",
    name = "beltometer-default-time-unit",
    setting_type = "runtime-per-user",
    default_value = "sec",
    allowed_values = {"sec", "min", "hour"},
    order = "b",
  },
  {
    type = "string-setting",
    name = "beltometer-default-avg-mode",
    setting_type = "runtime-per-user",
    default_value = "SMA",
    allowed_values = {"SMA", "EMA"},
    order = "c",
  },
  {
    type = "string-setting",
    name = "beltometer-default-display-mode",
    setting_type = "runtime-per-user",
    default_value = "total",
    allowed_values = {"total", "per_item"},
    order = "d",
  },
  {
    type = "double-setting",
    name = "beltometer-default-ema-alpha",
    setting_type = "runtime-per-user",
    default_value = 0.3,
    minimum_value = 0.01,
    maximum_value = 0.99,
    order = "e",
  },
})
